### ISSUE TITLE
Extra features

### ISSUE THREAD

**Issue by misa-coder** [Snowflake107/quickmongo#1]
Features like support for dot notation is really appreciated. 

Eg: db.set('hello.world', 'randomQuote')

Will create hello key with {world: 'randomQuote'} value.

**Comment by zyrouge** [comment]
👀 yes

**Comment by misa-coder** [comment]
Why closed

**Comment by Snowflake107** [comment]
**[Done](https://github.com/Snowflake107/quickmongo/releases/tag/v2)**! Try it with `QuickMongo v2`
